### ISSUE TITLE
Error appears when I tried to redeemed coupon

### ISSUE THREAD

**Issue by lxm218** [tearust/tea-browser-wallet#164] opened 2021-08-10 21:54 UTC
I don't know why this error appeared here

![image](https://user-images.githubusercontent.com/12605218/128940120-60e2e316-a314-4b5e-bd81-4a626de1a6ee.png)

**Comment by lxm218** [comment] 2021-08-10 21:56
after I refresh the page a few times, My coupon tab disappeared

**Comment by liyangwood** [comment] 2021-08-11 01:10
I can reproduce it.
the layer1 error is "NotEnoughDrawSeeds".
@raindust  please have a look to make sure the coupon expired logic is correct.

**Comment by raindust** [comment] 2021-08-12 09:05
![image](https://user-images.githubusercontent.com/3713930/129169448-25fef7c4-f97a-4ced-bc1b-5e078cfe0787.png)
In our old voucher csv file, our investors have too many vouchers however inventory is insufficient (total 100 seeds, 40% for investors so total investor seeds count is 40), this is why this error occurs.

Maybe we should check the voucher csv file later if we want to use a new one.

**Comment by kevingzhang** [comment] 2021-08-12 09:12
caused by insufficient genesis seeds. fixed by add more seeds

**Closed by kevingzhang** 2021-08-12 09:12 UTC
